"""created docs table

Revision ID: 624d82f41399
Revises: 
Create Date: 2020-04-28 10:50:29.224891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624d82f41399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reuters_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('categories', sa.String(length=255), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reuters_docs_doc_id'), 'reuters_docs', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reuters_docs_doc_id'), table_name='reuters_docs')
    op.drop_table('reuters_docs')
    # ### end Alembic commands ###
