"""added quote and entity tables

Revision ID: 7dbbb9796056
Revises: 624d82f41399
Create Date: 2020-04-28 10:51:32.063585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbbb9796056'
down_revision = '624d82f41399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reuters_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('_doc_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['_doc_id'], ['reuters_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reuters_entity_doc_id'), 'reuters_entity', ['doc_id'], unique=False)
    op.create_index(op.f('ix_reuters_entity_name'), 'reuters_entity', ['name'], unique=False)
    op.create_table('reuters_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('_doc_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.Integer(), nullable=True),
    sa.Column('suffix', sa.Integer(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('entity_start', sa.Integer(), nullable=True),
    sa.Column('entity_end', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_doc_id'], ['reuters_docs.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['reuters_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reuters_quote_doc_id'), 'reuters_quote', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reuters_quote_doc_id'), table_name='reuters_quote')
    op.drop_table('reuters_quote')
    op.drop_index(op.f('ix_reuters_entity_name'), table_name='reuters_entity')
    op.drop_index(op.f('ix_reuters_entity_doc_id'), table_name='reuters_entity')
    op.drop_table('reuters_entity')
    # ### end Alembic commands ###
